export const NAV_SECTIONS: Array<{ id: string; label: string } | { group: string }> = [
  { id: 'intro', label: 'Introduction' },
  { group: 'Getting Started' },
  { id: 'installation', label: 'Installation' },
  { id: 'quick-start', label: 'Quick Start' },
  { group: 'Examples' },
  { id: 'views', label: 'Views' },
  { id: 'showcase', label: 'Showcase' },
  { id: 'event-creation', label: 'Event Creation' },
  { id: 'drag-and-drop', label: 'Drag & Drop' },
  { id: 'popovers', label: 'Popovers' },
  { id: 'controlled', label: 'Controlled Mode' },
  { group: 'Customization' },
  { id: 'custom-toolbar', label: 'Custom Toolbar' },
  { id: 'custom-slots', label: 'Custom Slots' },
  { id: 'typed-metadata', label: 'Typed Metadata' },
  { id: 'theming', label: 'Theming' },
  { group: 'Integrations' },
  { id: 'shadcn', label: 'shadcn/ui' },
  { id: 'tailwind', label: 'Tailwind CSS' },
  { group: 'Reference' },
  { id: 'api', label: 'API Reference' },
  { id: 'hooks', label: 'Hooks' },
  { id: 'css-variables', label: 'CSS Variables' },
];
